# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Translate.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from Common.rewrite import *
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(670, 467)
        MainWindow.setMinimumSize(QtCore.QSize(670, 467))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.main_Button = QtWidgets.QPushButton(self.centralwidget)
        self.main_Button.setObjectName("main_Button")
        self.gridLayout.addWidget(self.main_Button, 0, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setText("")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 2, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.textEdit_2 = TextEdit()
        self.textEdit_2.setReadOnly(False)
        self.textEdit_2.setObjectName("textEdit_2")
        self.verticalLayout_2.addWidget(self.textEdit_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.upload_Button = QtWidgets.QPushButton(self.centralwidget)
        self.upload_Button.setObjectName("upload_Button")
        self.horizontalLayout.addWidget(self.upload_Button)
        self.comboBox_ocr = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_ocr.setObjectName("comboBox_ocr")
        self.horizontalLayout.addWidget(self.comboBox_ocr)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 3, 2, 1)
        self.ocr_textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.ocr_textEdit.setReadOnly(True)
        self.ocr_textEdit.setObjectName("ocr_textEdit")
        self.gridLayout.addWidget(self.ocr_textEdit, 0, 4, 2, 1)
        self.tips_textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.tips_textEdit.setReadOnly(True)
        self.tips_textEdit.setObjectName("tips_textEdit")
        self.gridLayout.addWidget(self.tips_textEdit, 1, 0, 1, 3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.horizontalLayout_2.addWidget(self.plainTextEdit)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.comboBox_1 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_1.setObjectName("comboBox_1")
        self.verticalLayout.addWidget(self.comboBox_1)
        self.translate_Button = QtWidgets.QPushButton(self.centralwidget)
        self.translate_Button.setObjectName("translate_Button")
        self.verticalLayout.addWidget(self.translate_Button)
        self.clear_Button = QtWidgets.QPushButton(self.centralwidget)
        self.clear_Button.setObjectName("clear_Button")
        self.verticalLayout.addWidget(self.clear_Button)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.plainTextEdit_2 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit_2.setReadOnly(True)
        self.plainTextEdit_2.setObjectName("plainTextEdit_2")
        self.horizontalLayout_2.addWidget(self.plainTextEdit_2)
        self.gridLayout.addLayout(self.horizontalLayout_2, 2, 0, 1, 5)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "momofish-Translate"))
        self.main_Button.setText(_translate("MainWindow", "主界面"))
        self.upload_Button.setText(_translate("MainWindow", "开始识别"))
        self.translate_Button.setText(_translate("MainWindow", "Translate"))
        self.clear_Button.setText(_translate("MainWindow", "Clear"))
