# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Translate.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(670, 467)
        MainWindow.setMinimumSize(QtCore.QSize(670, 467))
        MainWindow.setMaximumSize(QtCore.QSize(670, 467))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.main_Button = QtWidgets.QPushButton(self.centralwidget)
        self.main_Button.setGeometry(QtCore.QRect(20, 10, 91, 32))
        self.main_Button.setObjectName("main_Button")
        self.tips_plainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.tips_plainTextEdit.setGeometry(QtCore.QRect(20, 50, 351, 121))
        self.tips_plainTextEdit.setReadOnly(True)
        self.tips_plainTextEdit.setObjectName("tips_plainTextEdit")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(21, 184, 647, 194))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.plainTextEdit_1 = QtWidgets.QPlainTextEdit(self.layoutWidget)
        self.plainTextEdit_1.setObjectName("plainTextEdit_1")
        self.horizontalLayout.addWidget(self.plainTextEdit_1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.translate_Button = QtWidgets.QPushButton(self.layoutWidget)
        self.translate_Button.setObjectName("translate_Button")
        self.verticalLayout.addWidget(self.translate_Button)
        self.clear_Button = QtWidgets.QPushButton(self.layoutWidget)
        self.clear_Button.setObjectName("clear_Button")
        self.verticalLayout.addWidget(self.clear_Button)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.plainTextEdit_2 = QtWidgets.QPlainTextEdit(self.layoutWidget)
        self.plainTextEdit_2.setReadOnly(True)
        self.plainTextEdit_2.setObjectName("plainTextEdit_2")
        self.horizontalLayout.addWidget(self.plainTextEdit_2)
        self.pic_label = QtWidgets.QLabel(self.centralwidget)
        self.pic_label.setGeometry(QtCore.QRect(510, 10, 141, 161))
        self.pic_label.setText("")
        self.pic_label.setScaledContents(True)
        self.pic_label.setObjectName("pic_label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "momofish-Translate"))
        self.main_Button.setText(_translate("MainWindow", "主界面"))
        self.translate_Button.setText(_translate("MainWindow", "Translate"))
        self.clear_Button.setText(_translate("MainWindow", "Clear"))
